name: Run Cypress Tests
on: [push]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: cypress run
      uses: cypress-io/github-action@v3
      with:
        browser: chrome
        headless: true
        start: npm run cypress:run
      