name: Run Cypress Tests
on: [push]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: cypress run
      uses: cypress-io/github-action@v3
      with:
        browser: chrome
        headless: true
        start: npm run cypress:run
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress-screenshots
        path: cypress/screenshots  
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: cypress-videos
        path: cypress/videos
        
      
